config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :subscription_payments

  resources :subscriptions

  resources :activities
  get "routes/generateRunSheetsForAllRoutesForPDF"
  get "/routes/showRunSheets"
  get "/routes/generatePDFForRunSheets"
  get "routes/downloadPDFForRunSheets"	
  get "routes/generateCSVForRunSheets"	
  resources :runs

  resources :members

  resources :routes

   root 'welcome#index'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :route
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:subscription_id, :route_id, :run_sequence, :number, :street, :qty, :qty_comp, :service_notes, :last_name, :first_name, :phone_number, :email, :city, :state, :zip, :started_date, :last_letter_sent_date, :renewal_x0020_grp, :sold_x0020_By, :subscription_amount, :maint, :subscription_notes, :renewal_due_date, :subscription_status, :alternative_invoice, :map_date)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subscription_id %><br>
    <%= f.text_field :subscription_id %>
  </div>
  <div class="field">
    <%= f.label :route_id %><br>
    <%= f.text_field :route_id %>
  </div>
  <div class="field">
    <%= f.label :run_sequence %><br>
    <%= f.number_field :run_sequence %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.number_field :qty %>
  </div>
  <div class="field">
    <%= f.label :qty_comp %><br>
    <%= f.number_field :qty_comp %>
  </div>
  <div class="field">
    <%= f.label :service_notes %><br>
    <%= f.text_area :service_notes %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :started_date %><br>
    <%= f.datetime_select :started_date %>
  </div>
  <div class="field">
    <%= f.label :last_letter_sent_date %><br>
    <%= f.datetime_select :last_letter_sent_date %>
  </div>
  <div class="field">
    <%= f.label :renewal_x0020_grp %><br>
    <%= f.text_field :renewal_x0020_grp %>
  </div>
  <div class="field">
    <%= f.label :sold_x0020_By %><br>
    <%= f.text_field :sold_x0020_By %>
  </div>
  <div class="field">
    <%= f.label :subscription_amount %><br>
    <%= f.text_field :subscription_amount %>
  </div>
  <div class="field">
    <%= f.label :maint %><br>
    <%= f.text_field :maint %>
  </div>
  <div class="field">
    <%= f.label :subscription_notes %><br>
    <%= f.text_area :subscription_notes %>
  </div>
  <div class="field">
    <%= f.label :renewal_due_date %><br>
    <%= f.datetime_select :renewal_due_date %>
  </div>
  <div class="field">
    <%= f.label :subscription_status %><br>
    <%= f.text_field :subscription_status %>
  </div>
  <div class="field">
    <%= f.label :alternative_invoice %><br>
    <%= f.number_field :alternative_invoice %>
  </div>
  <div class="field">
    <%= f.label :map_date %><br>
    <%= f.datetime_select :map_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Subscription</th>
      <th>Route</th>
      <th>Run sequence</th>
      <th>Number</th>
      <th>Street</th>
      <th>Qty</th>
      <th>Qty comp</th>
      <th>Service notes</th>
      <th>Last name</th>
      <th>First name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Started date</th>
      <th>Last letter sent date</th>
      <th>Renewal x0020 grp</th>
      <th>Sold x0020 by</th>
      <th>Subscription amount</th>
      <th>Maint</th>
      <th>Subscription notes</th>
      <th>Renewal due date</th>
      <th>Subscription status</th>
      <th>Alternative invoice</th>
      <th>Map date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.subscription_id %></td>
        <td><%= subscription.route %></td>
        <td><%= subscription.run_sequence %></td>
        <td><%= subscription.number %></td>
        <td><%= subscription.street %></td>
        <td><%= subscription.qty %></td>
        <td><%= subscription.qty_comp %></td>
        <td><%= subscription.service_notes %></td>
        <td><%= subscription.last_name %></td>
        <td><%= subscription.first_name %></td>
        <td><%= subscription.phone_number %></td>
        <td><%= subscription.email %></td>
        <td><%= subscription.city %></td>
        <td><%= subscription.state %></td>
        <td><%= subscription.zip %></td>
        <td><%= subscription.started_date %></td>
        <td><%= subscription.last_letter_sent_date %></td>
        <td><%= subscription.renewal_x0020_grp %></td>
        <td><%= subscription.sold_x0020_By %></td>
        <td><%= subscription.subscription_amount %></td>
        <td><%= subscription.maint %></td>
        <td><%= subscription.subscription_notes %></td>
        <td><%= subscription.renewal_due_date %></td>
        <td><%= subscription.subscription_status %></td>
        <td><%= subscription.alternative_invoice %></td>
        <td><%= subscription.map_date %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subscription:</strong>
  <%= @subscription.subscription_id %>
</p>

<p>
  <strong>Route:</strong>
  <%= @subscription.route %>
</p>

<p>
  <strong>Run sequence:</strong>
  <%= @subscription.run_sequence %>
</p>

<p>
  <strong>Number:</strong>
  <%= @subscription.number %>
</p>

<p>
  <strong>Street:</strong>
  <%= @subscription.street %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @subscription.qty %>
</p>

<p>
  <strong>Qty comp:</strong>
  <%= @subscription.qty_comp %>
</p>

<p>
  <strong>Service notes:</strong>
  <%= @subscription.service_notes %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @subscription.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @subscription.first_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @subscription.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<p>
  <strong>City:</strong>
  <%= @subscription.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @subscription.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @subscription.zip %>
</p>

<p>
  <strong>Started date:</strong>
  <%= @subscription.started_date %>
</p>

<p>
  <strong>Last letter sent date:</strong>
  <%= @subscription.last_letter_sent_date %>
</p>

<p>
  <strong>Renewal x0020 grp:</strong>
  <%= @subscription.renewal_x0020_grp %>
</p>

<p>
  <strong>Sold x0020 by:</strong>
  <%= @subscription.sold_x0020_By %>
</p>

<p>
  <strong>Subscription amount:</strong>
  <%= @subscription.subscription_amount %>
</p>

<p>
  <strong>Maint:</strong>
  <%= @subscription.maint %>
</p>

<p>
  <strong>Subscription notes:</strong>
  <%= @subscription.subscription_notes %>
</p>

<p>
  <strong>Renewal due date:</strong>
  <%= @subscription.renewal_due_date %>
</p>

<p>
  <strong>Subscription status:</strong>
  <%= @subscription.subscription_status %>
</p>

<p>
  <strong>Alternative invoice:</strong>
  <%= @subscription.alternative_invoice %>
</p>

<p>
  <strong>Map date:</strong>
  <%= @subscription.map_date %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>