config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :subscription_payments

  resources :subscriptions

  resources :activities
  get "routes/generateRunSheetsForAllRoutesForPDF"
  get "/routes/showRunSheets"
  get "/routes/generatePDFForRunSheets"
  get "routes/downloadPDFForRunSheets"	
  get "routes/generateCSVForRunSheets"	
  resources :runs

  resources :members

  resources :routes

   root 'welcome#index'

end

app/models/run.rb
class Run < ActiveRecord::Base
  belongs_to :route
  belongs_to :member
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: [:show, :edit, :update, :destroy]

  # GET /runs
  # GET /runs.json
  def index
    @runs = Run.all
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
  end

  # GET /runs/new
  def new
    @run = Run.new
  end

  # GET /runs/1/edit
  def edit
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(run_params)

    respond_to do |format|
      if @run.save
        format.html { redirect_to @run, notice: 'Run was successfully created.' }
        format.json { render :show, status: :created, location: @run }
      else
        format.html { render :new }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to @run, notice: 'Run was successfully updated.' }
        format.json { render :show, status: :ok, location: @run }
      else
        format.html { render :edit }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url, notice: 'Run was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.require(:run).permit(:run_id, :route_id, :member_id, :run_date, :time_taken, :am_pm, :notes)
    end
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/_form.html.erb
<%= form_for(@run) do |f| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :run_id %><br>
    <%= f.text_field :run_id %>
  </div>
  <div class="field">
    <%= f.label :route_id %><br>
    <%= f.text_field :route_id %>
  </div>
  <div class="field">
    <%= f.label :member_id %><br>
    <%= f.text_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :run_date %><br>
    <%= f.datetime_select :run_date %>
  </div>
  <div class="field">
    <%= f.label :time_taken %><br>
    <%= f.number_field :time_taken %>
  </div>
  <div class="field">
    <%= f.label :am_pm %><br>
    <%= f.text_field :am_pm %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runs/edit.html.erb
<h1>Editing run</h1>

<%= render 'form' %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

app/views/runs/index.html.erb
<h1>Listing runs</h1>

<table>
  <thead>
    <tr>
      <th>Run</th>
      <th>Route</th>
      <th>Member</th>
      <th>Run date</th>
      <th>Time taken</th>
      <th>Am pm</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @runs.each do |run| %>
      <tr>
        <td><%= run.run_id %></td>
        <td><%= run.route %></td>
        <td><%= run.member %></td>
        <td><%= run.run_date %></td>
        <td><%= run.time_taken %></td>
        <td><%= run.am_pm %></td>
        <td><%= run.notes %></td>
        <td><%= link_to 'Show', run %></td>
        <td><%= link_to 'Edit', edit_run_path(run) %></td>
        <td><%= link_to 'Destroy', run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Run', new_run_path %>

app/views/runs/new.html.erb
<h1>New run</h1>

<%= render 'form' %>

<%= link_to 'Back', runs_path %>

app/views/runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Run:</strong>
  <%= @run.run_id %>
</p>

<p>
  <strong>Route:</strong>
  <%= @run.route %>
</p>

<p>
  <strong>Member:</strong>
  <%= @run.member %>
</p>

<p>
  <strong>Run date:</strong>
  <%= @run.run_date %>
</p>

<p>
  <strong>Time taken:</strong>
  <%= @run.time_taken %>
</p>

<p>
  <strong>Am pm:</strong>
  <%= @run.am_pm %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @run.notes %>
</p>

<%= link_to 'Edit', edit_run_path(@run) %> |
<%= link_to 'Back', runs_path %>