config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :subscription_payments

  resources :subscriptions

  resources :activities
  get "routes/generateRunSheetsForAllRoutesForPDF"
  get "/routes/showRunSheets"
  get "/routes/generatePDFForRunSheets"
  get "routes/downloadPDFForRunSheets"	
  get "routes/generateCSVForRunSheets"	
  resources :runs

  resources :members

  resources :routes

   root 'welcome#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :member
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:activity_id, :member_id, :activity_date, :activity_ampm, :activity_type, :activity_unit_count)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity_id %><br>
    <%= f.text_field :activity_id %>
  </div>
  <div class="field">
    <%= f.label :member_id %><br>
    <%= f.text_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :activity_date %><br>
    <%= f.datetime_select :activity_date %>
  </div>
  <div class="field">
    <%= f.label :activity_ampm %><br>
    <%= f.text_field :activity_ampm %>
  </div>
  <div class="field">
    <%= f.label :activity_type %><br>
    <%= f.text_field :activity_type %>
  </div>
  <div class="field">
    <%= f.label :activity_unit_count %><br>
    <%= f.number_field :activity_unit_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <thead>
    <tr>
      <th>Activity</th>
      <th>Member</th>
      <th>Activity date</th>
      <th>Activity ampm</th>
      <th>Activity type</th>
      <th>Activity unit count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.activity_id %></td>
        <td><%= activity.member %></td>
        <td><%= activity.activity_date %></td>
        <td><%= activity.activity_ampm %></td>
        <td><%= activity.activity_type %></td>
        <td><%= activity.activity_unit_count %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Activity:</strong>
  <%= @activity.activity_id %>
</p>

<p>
  <strong>Member:</strong>
  <%= @activity.member %>
</p>

<p>
  <strong>Activity date:</strong>
  <%= @activity.activity_date %>
</p>

<p>
  <strong>Activity ampm:</strong>
  <%= @activity.activity_ampm %>
</p>

<p>
  <strong>Activity type:</strong>
  <%= @activity.activity_type %>
</p>

<p>
  <strong>Activity unit count:</strong>
  <%= @activity.activity_unit_count %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>