config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :subscription_payments

  resources :subscriptions

  resources :activities
  get "routes/generateRunSheetsForAllRoutesForPDF"
  get "/routes/showRunSheets"
  get "/routes/generatePDFForRunSheets"
  get "routes/downloadPDFForRunSheets"	
  get "routes/generateCSVForRunSheets"	
  resources :runs

  resources :members

  resources :routes

   root 'welcome#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:member_id, :member_last_name, :member_first_name, :member_cell, :member_landline, :member_email, :memberInactive, :member_vehicle)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br>
    <%= f.text_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :member_last_name %><br>
    <%= f.text_field :member_last_name %>
  </div>
  <div class="field">
    <%= f.label :member_first_name %><br>
    <%= f.text_field :member_first_name %>
  </div>
  <div class="field">
    <%= f.label :member_cell %><br>
    <%= f.text_field :member_cell %>
  </div>
  <div class="field">
    <%= f.label :member_landline %><br>
    <%= f.text_field :member_landline %>
  </div>
  <div class="field">
    <%= f.label :member_email %><br>
    <%= f.text_field :member_email %>
  </div>
  <div class="field">
    <%= f.label :memberInactive %><br>
    <%= f.check_box :memberInactive %>
  </div>
  <div class="field">
    <%= f.label :member_vehicle %><br>
    <%= f.text_field :member_vehicle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <thead>
    <tr>
      <th>Member</th>
      <th>Member last name</th>
      <th>Member first name</th>
      <th>Member cell</th>
      <th>Member landline</th>
      <th>Member email</th>
      <th>Memberinactive</th>
      <th>Member vehicle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.member_id %></td>
        <td><%= member.member_last_name %></td>
        <td><%= member.member_first_name %></td>
        <td><%= member.member_cell %></td>
        <td><%= member.member_landline %></td>
        <td><%= member.member_email %></td>
        <td><%= member.memberInactive %></td>
        <td><%= member.member_vehicle %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @member.member_id %>
</p>

<p>
  <strong>Member last name:</strong>
  <%= @member.member_last_name %>
</p>

<p>
  <strong>Member first name:</strong>
  <%= @member.member_first_name %>
</p>

<p>
  <strong>Member cell:</strong>
  <%= @member.member_cell %>
</p>

<p>
  <strong>Member landline:</strong>
  <%= @member.member_landline %>
</p>

<p>
  <strong>Member email:</strong>
  <%= @member.member_email %>
</p>

<p>
  <strong>Memberinactive:</strong>
  <%= @member.memberInactive %>
</p>

<p>
  <strong>Member vehicle:</strong>
  <%= @member.member_vehicle %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>